spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    cluster:
      nodes: 192.168.1.60:6379,192.168.1.60:6380,192.168.1.60:6381,192.168.1.60:6382,192.168.1.60:6383,192.168.1.60:6384
      max-redirects: 6